### ISSUE TITLE
running time of segmentation

### ISSUE THREAD

**Issue by Hanminghao** [HKU-MedAI/WSI-HGNN#1]
Very good work, I would like to ask you about how long it took you to use Hover-Net for wsi image segmentation of BRCA data sets? It takes me about half an hour to segment a wsi picture using 4*RTX A6000(48GB). Is this time too long? Looking forward to your reply.

**Comment by howardchanth** [comment]
Hi thanks for your interest. If I understand correctly you are talking about the Hover-Net prediction for the node types (i.e., pseudo-label). As you can see in the implementations for HoverNet we process the patches in batches, and from our experience constructing a graph (from a BRCA wsi) takes about five minutes using one GPU (around RTX 20xx, 16GB). For Camelyon 16 it takes about half an hour since the WSI is much larger.
