### ISSUE TITLE
About the ./checkpoints and ./data file folders

### ISSUE THREAD

**Issue by WkEEn** [HKU-MedAI/WSI-HGNN#3]
Hi! I will be very appreciated if you can upload the ./checkpoints and ./data to share the weights of pretrianed hovernet and Kiamianet with their json files.

**Comment by trinhvg** [comment]
Please share your ./data  folder, or your ground-truth files, since number of cases in your paper doesn't match with tcga portal, I guess you removed low quality sample?

**Comment by howardchanth** [comment]
For the weights of Kimianet and HoverNet they can be easily obtained from their original works. Please see #6 for the discussion.

I have uploaded the example label files in the ./data folder. The ground truth is referred to the nationwidechildrens.org_clinical_patient_[DATASET].txt under the clinical data in the TCGA portal. Detail discussions can be found in #5 and #2. For WSI preprocessing, since some (a small number) WSIs are very small and we cannot extract meaningful patches at a certain level, these are removed by the standard tiler we used (i.e., from DSMIL), which is common in WSI preprocessing.
